# permissions for end users to edit inferencepipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: inferencepipeline-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kai
    app.kubernetes.io/part-of: kai
    app.kubernetes.io/managed-by: kustomize
  name: inferencepipeline-editor-role
rules:
- apiGroups:
  - ai.kai.io
  resources:
  - inferencepipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ai.kai.io
  resources:
  - inferencepipelines/status
  verbs:
  - get
