apiVersion: core.kai.io/v1alpha1
kind: Step
metadata:
  name: http-echo
spec:
  containers:
  - name: http-echo
    image: "hashicorp/http-echo"
    args: ["-listen=:9001", "-text=hello from version 1"]
    ports:
    - containerPort: 9001