apiVersion: core.kai.io/v1alpha1
kind: ModelRuntime
metadata:
  name: pytorch-runtime
spec:
  supportedModelFormats:
  - pytorch
  containers:
  - name: kai-container
    image: "pytorch/torchserve-kfs:0.7.0"
    args: ["torchserve", "--start", "--model-store=/mnt/models/model-store", "--ts-config=/mnt/models/config/config.properties"]
    ports:
    - containerPort: 8085
---
apiVersion: core.kai.io/v1alpha1
kind: Step
metadata:
  name: image-classifier
spec:
  model:
    modelFormat: pytorch
    uri: gs://kfserving-examples/models/torchserve/image_classifier/v1
